# -*- coding: utf-8 -*-
"""module1hard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13wM8KIuUyXCYBuowCZA6XDfHywe1q0PH

module1hard
"""

import numpy as np
grades = [[5, 3, 3, 5, 4], [2, 2, 2, 3], [4, 5, 5, 2], [4, 4, 3], [5, 5, 5, 4, 5]]
students = {'Johnny', 'Bilbo', 'Steve', 'Khendrik', 'Aaron'}
students = list(students)
mean = []
for g, s in zip(grades, students):
    mean.append((sum(g)/len(g)))

res = dict(zip(students, mean))
print (dict(sorted(res.items())))